{
	"schema_version": "1.6.0",
	"id": "PYSEC-2022-43134",
	"modified": "2024-11-21T14:57:02.697023Z",
	"published": "2022-08-27T20:15:00Z",
	"aliases": [
		"CVE-2022-38792",
		"GHSA-cv6j-9835-p7fh"
	],
	"details": "The exotel (aka exotel-py) package in PyPI as of 0.1.6 includes a code execution backdoor inserted by a third party.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "exotel",
				"purl": "pkg:pypi/exotel"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"0.1.0",
				"0.1.1",
				"0.1.3",
				"0.1.4",
				"0.1.5"
			],
			"database_specific": {
				"source": "https://github.com/pypa/advisory-database/blob/main/vulns/exotel/PYSEC-2022-43134.yaml"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://github.com/jertel/elastalert2/pull/931"
		},
		{
			"type": "WEB",
			"url": "https://inspector.pypi.io/project/exotel/0.1.6/packages/8b/ed/9ebeb34d4adb9b01151d73ccfde9c1cb2d629c3b146953c8727559a65446/exotel-0.1.6.tar.gz/exotel-0.1.6/setup.py"
		},
		{
			"type": "PACKAGE",
			"url": "https://pypi.org/project/exotel/"
		},
		{
			"type": "REPORT",
			"url": "https://github.com/sarathsp06/exotel-py/issues/10"
		}
	]
}
