{
	"schema_version": "1.6.0",
	"id": "MAL-2024-11588",
	"modified": "2024-12-09T06:50:13Z",
	"published": "2024-12-09T06:50:13Z",
	"summary": "Malicious code in fadlearner (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "fadlearner",
				"purl": "pkg:pypi/fadlearner"
			},
			"versions": [
				"912.6"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/fadlearner/MAL-2024-11588.json"
			}
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-11039",
				"import_time": "2024-12-09T14:38:43.66664796Z",
				"modified_time": "2024-12-09T06:50:13Z",
				"sha256": "baedab409cb9db89ca8ea7d619157796ba152c4b2bc65beaa041d21e822b633b",
				"source": "reversing-labs",
				"versions": [
					"912.6"
				]
			}
		]
	}
}
