{
	"schema_version": "1.6.0",
	"id": "MAL-2024-11629",
	"modified": "2024-12-09T06:50:33Z",
	"published": "2024-12-09T06:50:33Z",
	"summary": "Malicious code in malware-test-pack-new (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "malware-test-pack-new",
				"purl": "pkg:pypi/malware-test-pack-new"
			},
			"versions": [
				"0.0.4"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/malware-test-pack-new/MAL-2024-11629.json"
			}
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-11083",
				"import_time": "2024-12-09T14:38:45.420483232Z",
				"modified_time": "2024-12-09T06:50:33Z",
				"sha256": "6b11574e21efead8eb9a689998b4df383c5e33955ceb6bf84d8a884c74904d6a",
				"source": "reversing-labs",
				"versions": [
					"0.0.4"
				]
			}
		]
	}
}
