{
	"schema_version": "1.6.0",
	"id": "MAL-2024-6086",
	"modified": "2024-06-28T03:27:24.330184Z",
	"published": "2024-06-25T13:43:11Z",
	"aliases": [
		"SNYK-PYTHON-SYSSQLITEADDV2-5932128"
	],
	"summary": "Malicious code in syssqliteaddv2 (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "syssqliteaddv2",
				"purl": "pkg:pypi/syssqliteaddv2"
			},
			"versions": [
				"1.1.0",
				"1.0.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/syssqliteaddv2/MAL-2024-6086.json"
			}
		}
	],
	"references": [
		{
			"type": "ARTICLE",
			"url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-SYSSQLITEADDV2-5932128"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-04889",
				"import_time": "2024-06-28T02:50:54.525908862Z",
				"modified_time": "2024-06-25T13:43:11Z",
				"sha256": "3a06d1c68884ec01bcf4f82ff9bb70af6bd5b10ddf8cc99a397617cd635cac04",
				"source": "reversing-labs",
				"versions": [
					"1.1.0",
					"1.0.0"
				]
			}
		]
	}
}
