{
	"schema_version": "1.6.0",
	"id": "MAL-2024-6169",
	"modified": "2024-10-24T01:01:59Z",
	"published": "2024-06-25T13:43:50Z",
	"aliases": [
		"SNYK-PYTHON-TRYCONF-5885066"
	],
	"summary": "Malicious code in tryconf (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "tryconf",
				"purl": "pkg:pypi/tryconf"
			},
			"versions": [
				"0.1"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/tryconf/MAL-2024-6169.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-TRYCONF-5885066"
		},
		{
			"type": "WEB",
			"url": "https://github.com/DataDog/malicious-software-packages-dataset"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-04973",
				"import_time": "2024-06-28T02:51:04.407797021Z",
				"modified_time": "2024-06-25T13:43:50Z",
				"sha256": "139aecb84977d3d532ab79b36feeb1a0e4df7c49b9ee81f7e4708d4ba693236b",
				"source": "reversing-labs",
				"versions": [
					"0.1"
				]
			},
			{
				"id": "RLUA-2024-09450",
				"import_time": "2024-10-24T01:00:22.446644197Z",
				"modified_time": "2024-10-16T14:53:14Z",
				"sha256": "9e0eb70766d6f278ec34801c344c170051751c852fc679a6e70b661baf5c99d5",
				"source": "reversing-labs"
			}
		]
	}
}
