{
	"schema_version": "1.6.0",
	"id": "MAL-2024-4808",
	"modified": "2024-10-24T01:01:57Z",
	"published": "2024-06-25T13:32:44Z",
	"aliases": [
		"SNYK-PYTHON-BIPUTILE-6513244"
	],
	"summary": "Malicious code in bip-utile (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "bip-utile",
				"purl": "pkg:pypi/bip-utile"
			},
			"versions": [
				"1.0.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/bip-utile/MAL-2024-4808.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-BIPUTILE-6513244"
		},
		{
			"type": "ARTICLE",
			"url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-03588",
				"import_time": "2024-06-28T02:48:20.680462752Z",
				"modified_time": "2024-06-25T13:32:44Z",
				"sha256": "0d05be458a263e86aeea6c6b03234972f96fc068e33c7f48fdb1db96a42762a6",
				"source": "reversing-labs",
				"versions": [
					"1.0.0"
				]
			},
			{
				"id": "RLUA-2024-07867",
				"import_time": "2024-10-24T00:58:49.454465116Z",
				"modified_time": "2024-10-16T14:36:51Z",
				"sha256": "876e078df9fc722a49af519a6258c9c90eba4ccea9595e49c4b44626d78d9c71",
				"source": "reversing-labs"
			}
		]
	}
}
