{
	"schema_version": "1.6.0",
	"id": "MAL-2023-1391",
	"modified": "2023-05-20T14:05:50Z",
	"published": "2023-05-20T14:05:50Z",
	"summary": "Malicious code in pygame-pytorch (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n\n## Source: ossf-package-analysis (c104a6d866e764da7907147cd7def349f360987498156433ef1e11bf4ac2263c)\nThe OpenSSF Package Analysis project identified 'pygame-pytorch' @ 3.4.19 (pypi) as malicious.\n\nIt is considered malicious because:\n- The package communicates with a domain associated with malicious activity.\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "pygame-pytorch",
				"purl": "pkg:pypi/pygame-pytorch"
			},
			"versions": [
				"3.4.19"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/malicious/pypi/pygame-pytorch/MAL-2023-1391.json"
			}
		}
	],
	"credits": [
		{
			"name": "OpenSSF: Package Analysis",
			"contact": [
				"https://github.com/ossf/package-analysis",
				"https://openssf.slack.com/channels/package_analysis"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"import_time": "2023-08-10T06:17:12.264275741Z",
				"modified_time": "2023-05-20T14:05:50.399721796Z",
				"sha256": "c104a6d866e764da7907147cd7def349f360987498156433ef1e11bf4ac2263c",
				"source": "ossf-package-analysis",
				"versions": [
					"3.4.19"
				]
			}
		]
	}
}
